---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    yum:
     update_cache: yes

  - name: install apache2 package
    yum:
     name: httpd
     state: present
  - name: libapache2-mod install
    yum:
     name: ansible
     state: absent

